[package]
name = "cpu_6502"
version = "0.1.0"
authors = ["Mark Asp <mark.asp@osii.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser_6502 = { path = "../parser_6502" }
