[package]
name = "parser_6502"
version = "0.1.0"
authors = ["Mark Asp <asp.mark.steven@gmail.com>"]
edition = "2018"

[dev-dependencies]
claim = "0.3.1"

[dependencies]
logos = "0.11.4"
enum_string = { path = "../enum_string" }
smallvec = "1.4.0"
bytes = "0.5.5"
lazy_static = "1.4.0"